### ISSUE TITLE
Framebuffer upscaling

### ISSUE THREAD

**Issue by WAHa06x36** [raspberrypi/firmware#104]
Would it be possible to have an option, either in config.txt or perhaps more preferably in the mailbox interface, for configuring the type of upscaling used on the framebuffer?

I have been toying around with writing some games for the Pi rendering directly to the framebuffer on the bare metal, and it's working well so far, except for one thing: A low-resolution framebuffer looks very ugly when displaying pixel graphics, due to the smooth upscaling.

I assume the GPU upscales the framebuffer to the resolution set in config.txt, which is pretty useful, but it would look a lot better if it was upscaled using nearest-neighbour rather than the bilinear or whatever it is using right now.

Ideally, I'd like three options:
1. The current interpolated scaling
2. Nearest-neighbour scaling
3. Nearest-neighbout scaling up to the largest integer factor that will fit in the native resolution, with black bars around it. For instance, 320x240 should be upscaled to 960x720 (3x) if the native resolution is 1024x768.

Number 3 might be asking a bit much, but at least number 2 would be really nice to have.

**Comment by objectchris** [comment]
Sorry for bumping this old (closed) issue, but is there a way of changing the scaling at runtime, rather than this global setting?

For example, I'm running an emulation system, and within the UI I want the scaling at default (interpolated/bilinear) and looks great (unnoticeable, really). However, if I then launch a game using dispmanx and a low resolution framebuffer, it will apply the same scaling resulting in a blurry image. Likewise, if I use scaling_kernal=8, my game looks good, but the UI has scaling artifacts.

The driver being used is https://github.com/libretro/RetroArch/blob/aa488dda25c017bc224ca559a20f2d616bd00330/gfx/drivers/dispmanx_gfx.c - is it as simple as setting the scaling mode to 8 within the driver?

**Comment by popcornmix** [comment]
If you run:
```
$ vcgencmd scaling_kernel
scaling_kernel=0 -2 -6 -8 -10 -8 -3 2 18 50 82 119 155 187 213 227 227 213 187 155 119 82 50 18 2 -3 -8 -10 -8 -6 -2 0   0
```
it shows the current scaling kernel. You can change it at run time by passing the paramaters back.
```
$ vcgencmd scaling_kernel 0 -2 -6 -8 -10 -8 -3 2 18 50 82 119 155 187 213 227 227 213 187 155 119 82 50 18 2 -3 -8 -10 -8 -6 -2 0   0
scaling_kernel=0 -2 -6 -8 -10 -8 -3 2 18 50 82 119 155 187 213 227 227 213 187 155 119 82 50 18 2 -3 -8 -10 -8 -6 -2 0   0
```
So, capture the kernel for the default and the ``scaling_kernal=8`` cases and you can now switch between them at runtime.

**Comment by joolswills** [comment]
Is it possible to change the scaling used in individual cases when working with dispmanx in code ? eg when using vc_dispmanx_rect_set / vc_dispmanx_element_add etc ?

**Comment by popcornmix** [comment]
Per element scaling kernels is not supported.
