### ISSUE TITLE
RPI B3+ gets stuck on reboot when doing Netboot

### ISSUE THREAD

**Issue by Flole998** [raspberrypi/firmware#1088]
As mentioned at https://github.com/raspberrypi/firmware/issues/1078#issuecomment-451233345 in #1078 there is an issue when the pi reboots and gets stuck somewhere, apparently the issue is already reproducable.

**Comment by ghollingworth** [comment]
Yes, I've got a simple reproduction, which is to use 

`echo b > /proc/sysrq-trigger`
Or Alt + PrtScr + b on the keyboard

Which causes the lock up on reboot...  Currently it is locking up (and crashing hard) while trying to read from one of the files, this is caused by an exception or interrupt occuring during the bootcode.  Unclear at the moment what the cause is.

**Comment by popcornmix** [comment]
Potential fix now in latest rpi-update firmware

**Comment by Flole998** [comment]
> Potential fix now in latest rpi-update firmware

Are you sure? Note that this is not the netboot-on-different Subnet issue from #1078

**Comment by pelwell** [comment]
Yes - read the commit message:
```
...
bootcode: Reset WiFi and BT devices before resetting the expander
See: raspberrypi/firmware#1088
```

**Comment by Flole998** [comment]
Seems indeed fixed! Great!
