### ISSUE TITLE
Can't use SPI after GPIO on the same pins

### ISSUE THREAD

**Issue by qvas** [raspberrypi/firmware#170]
Hi!

I'm trying to write program that utilizes RPi output pins P1-03 and P1-03 as GPIO0 and GPIO1, and then open I2C device and exchange data with I2C device. It seems I2C driver doesn't change pins role at open procedure. E.g. if I open I2C after reboot everything works OK, but I2C connection is completely broken if GPIO devices was accessed at first. Is there any workaround how to bypass this bug without board rebooting?

**Comment by Ruffio** [comment]
@qvas is this still an issue?

**Comment by qvas** [comment]
Yes, it is still reproducible on "Linux raspberrypi 3.18.7+"

**Comment by pelwell** [comment]
This is expected behaviour. GPIOs and alt functions are allowed to "share" pins, but the intention is to allow people to use unused pins for GPIO. (Like @cleverca22 I think this is a mistake because it leads to issues like this, but it was a conscious upstream decision). The shift to using Device Tree and pinctrl for configuration has made drivers simpler and more portable, but the configuration is done when the platform device is created.

If your application changes one of the pins for its own purposes then it should change it back before expecting the previous owner to function correctly.

Not a bug.

**Comment by qvas** [comment]
Unfortunately using https://github.com/rewolff/bw_rpi_tools to change role back is not cross platform solution.   Otherwise фвмфтефпу of standard driver over wiringPi is under question.

**Comment by pelwell** [comment]
This is the first time you've mentioned cross platform solutions as being an issue for you. What do you do when you want to share pins like this on another platform?

**Comment by rewolff** [comment]
rmmod <somethingorother>-spi
modprobe <thesamething>

will work too to reassign the SPI pins back to the SPI module. It's more "cross platform". 

My bw_rpi_tools was written when there WAS next to nothing else. So there it is poking the wrong hardware registers if you have a 'pi 2. (i.e. that solution is not portable from pi to pi2. )

**Comment by qvas** [comment]
I'm supporting library that provides unified way to access a set of peripheral on different platforms (not only Linux).  Use of pin alternative functions is part of test cycle. Obviously it looks quite artificial but sometime this scenario helps to discover hidden implementation bugs.

**Comment by pelwell** [comment]
Which still leaves my question:
> What do you do when you want to share pins like this on another platform?
