### ISSUE TITLE
PiZ2W: different use of WiFi firmware

### ISSUE THREAD

**Issue by jayofelony** [raspberrypi/firmware#1869]
What is the reason for using different firmware for the same wifi chip in 2 different OS releases? This is taken from a Pi Zero 2W

![Screenshot from 2024-02-14 21-06-50](https://github.com/raspberrypi/firmware/assets/50277312/b5176497-1c1f-4789-ba3a-57a3307fdc18)
RaspiOS Bullseye arm64
-
![Screenshot from 2024-02-14 20-29-18](https://github.com/raspberrypi/firmware/assets/50277312/aeb239da-e73b-4793-a736-915eecd7faf7)
RaspiOS Bookworm arm64
-

**Comment by pelwell** [comment]
> What is the reason for using different firmware for the same wifi chip in 2 different OS releases?

The firmware is the same - look at the version strings (*). However, the two OSes load it via different names.

Bullseye used a hacked brcmfmac driver that pulled the firmware names from Device Tree. This was necessary because the Synaptics 43436s has the same SDIO ID as the Cypress 43430/43438, but they should run the corresponding firmware. The kernel used in Bookworm had gained the ability to qualify the firmware names with the board model string (also from DT), which means we can create bcrmcfmac43430-sdio.raspberrypi,model-zero-2-w.bin as a symbolic link to brcmfmac43436s-sdio.bin and drop the kernel patch.

But obviously, wait to see what the experts on the nexmon repo say.

(*) I don't recognise that version string - it's not what ships with Bookworm - so I think you've already modified your system.

**Comment by jayofelony** [comment]
Yeah this is running nexmon indeed. But we came across some weird things. As mentioned in the nexmon issue. It seems a hardware vs software thing.

**Comment by pelwell** [comment]
I think I've answered your question, even though this isn't the forum for general questions, and we don't and won't support nexmon.
