### ISSUE TITLE
MMC boot compatibility

### ISSUE THREAD

**Issue by thexeno** [raspberrypi/firmware#187]
Hi! I'm trying to use a dual voltage mmc of 2GB, labeled Kingston., to burn a raspbian image on it. 
But i discovered that i can't, in the sense that everytime the ACT led is saying that the .elf file is not found (it flashes 3 times). But i know that, at least months ago, the mmc has been used.

There's any compatibility issue with this memory? it can be downgraded the boot part to be compatible again?

**Comment by snajpa** [comment]
Is it still possible to add MMC support to the boot firmware? I would gladly send a dozen of MMCs to anyone willing to implement it.

The reason why I wish for MMC support is that I'm looking for a solution, how to boot without any real card, just a microcontroller acting as one (data will be on the network) - because I would like to abstract myself from having to solve flash wear out problem completely, I don't want to have any unreliable flash in the build cluster. (We're putting together a build farm for Fedora).

**Comment by popcornmix** [comment]
The bootrom is what initially reads the sd or mmc card and tries to load bootcode.bin.
This does support at least some MMC cards. If you get as far as LEDs flashing, then things are good. If you don't then it's probably not possible to support (the bootrom is not modifiable).

Assuming you get as far as flashing LEDs, but the Pi fails to fully boot, then it may be possible to fix in software. Getting an MMC card to @ghollingworth would be the first step.

**Comment by snajpa** [comment]
Thanks, @popcornmix, that sounds good. So I'll go ahead with implementing just MMC.

**Comment by NedScott** [comment]
If anyone is still interested in working on this, I still have a MMC card that I am willing to mail off to anywhere. You can even keep the card :)

**Comment by FalconFour** [comment]
I'd like to stop by here as well and offer my small pile of incompatible RS-MMC and MMCMobile cards to this cause. I have a project whose whole OS (based on Tiny Core Linux) and application all fit within the confines of a 128MB card, and there are plentiful listings of RS-MMC and MMCMobile cards on eBay that fit nicely into the Adafruit PiTFT enclosure without protruding (as full SD cards do). Thus, the RS-MMC form factor is an extremely useful bonus.

I'd been using MicroSD "shortening" adapters, but they're usually designed for MacBooks and they either protrude slightly (and are poorly manufactured, leaving intermittent connection issues), or have a SMD MicroSD carrier on top that requires enclosure modding to fit. But whenever I use a MicroSD card in an adapter, it always, always, always works.

With the RS-MMC/MMCMobile game, it's been a nightmare - 4 misses and 2 "hits" - as to what cards can be made to boot properly.
(All of these are given the same set of files to boot with, using Tiny Core Linux 6.1)
1) AData "MyFlash" 128MB RS-MMC cards, 13-pin (I bought 4 of these before knowing of a compatibility problem) - these give 7 blinks at best, with lots of debugging here --> https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=134285
2) ATP 512mb RS-MMC, 7-pin - 4 blinks.
3) Lexar 512mb MMCMobile, 13-pin - Boots to display, but gives a panic saying "unable to mount root fs on unknown-block(1,0)". It appears that, while it loaded the kernel image, it didn't also load the ramdisk image before handing it off to boot. Couldn't get this one working.
4) Sandisk 128MB RS-MMC, 7-pin - 4 blinks.
5) Kingston 1GB MMCMobile, 13-pin - works flawlessly. In fact, this was the first RS-MMC card I owned, and I later bought the others thinking that the RS-MMC form factor was more or less standard...
6) Kingston 512MB RS-MMC, 7-pin - works flawlessly (though noticeably slower to boot). Interesting that this is the first 7-pin card I've seen that boots. When I bought it, the display image was that of the 13-pin version - but it thankfully turned out to boot properly anyway.

So, who wants me to ship them cards 1 through 4? I have about 4 clones of the Adata 128mb card to send around as well, for what it's worth.

Also would love to know of any utilities that can help decode the capabilities of the card (per Wikipedia, https://en.wikipedia.org/wiki/MultiMediaCard#Table ) as to help explain why the boot loader is so picky about the cards it'll work with...
