### ISSUE TITLE
ISR has stopped working in the latest versions

### ISSUE THREAD

**Issue by JoaoEstrella** [raspberrypi/firmware#1878]
**Describe the bug**
I have an application using pigpio in C++. After updating to the latest version, the ISR functions stopped being called/working. There is no error message, they just aren't being called. After many tests, I reverted to some older versions with 'rpi-update' and everything started working correctly again.

**To reproduce**
gpioSetISRFunc() from pigpio (c++) does not work

**Expected behaviour**
work

**Actual behaviour**
In the latest versions, ISR functions are not called.

**System**
Following are the specifications of the working version

* Which model of Raspberry Pi?
  * Pi4B

* Which OS and version (`cat /etc/rpi-issue`)?
  * Raspberry Pi reference 2023-12-05
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 70cd6f2a1e34d07f5cba7047aea5b92457372e05, stage4

* Which firmware version (`vcgencmd version`)?
  * Oct 17 2023 15:39:16 
Copyright (c) 2012 Broadcom
version 30f0c5e4d076da3ab4f341d88e7d505760b93ad7 (clean) (release) (start)

 
* Which kernel version (`uname -a`)?
  *   Linux raspberrypi 6.1.70-v8+ #1712 SMP PREEMPT Tue Jan  2 18:31:53 GMT 2024 aarch64 GNU/Linux

**Comment by 6by9** [comment]
Accessing GPIOs via sysfs has been deprecated since 2015, and slated for removal at some time after 2020.

libgpiod is the supported interface for GPIO.
 
sysfs for GPIO is still there, but the 6.6 kernel has dropped forcing the GPIOs to start at 0 - that has been deprecated in mainline for several years, and since 6.2 has been actively logging errors if it finds a driver doing so.
Pi5 has never set the base to be 0, which is one of the reasons that pigpio doesn't support it.

pigpio could be updated to either find the relevant sysfs GPIO, but you may be better off looking at https://github.com/joan2937/lg which is the same author switching to libgpiod.
