### ISSUE TITLE
Possible to turn on LED on camera module v1.3 using code rather then GPIO

### ISSUE THREAD

**Issue by mrfoxie** [raspberrypi/firmware#1890]
- Kernel version
```text
Linux Server 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
```
- SBC model `Raspberry Pi 0 2W`
- Power supply used `Raspberry Pi 12.5W Micro USB Power Supply`
- SD card used `Sandisk 128GB Class A`

I have attached Raspberry Pi Camera Module 2 but in that LED is not been turning on although i have turned it on by editing `/boot/config.txt` and adding this line at the end of the config file `Disable_camera_led=0`
 the camera module, power supply, sdcard and pi is newly purchased

**Comment by 6by9** [comment]
This looks like a duplicate of https://forums.raspberrypi.com/viewtopic.php?t=369831 which has been answered, but anyway....

Pi Camera module v2 (https://www.raspberrypi.com/products/camera-module-v2/) has no LED.
Only the v1 (discontinued since around 2015 due to ov5647 being declared EOL) has ever had an LED.

Pi02 was released in 2021, so 5-6 years after the v1 had been discontinued, and due to a shortage of GPIOs from the SoC it has no connection to the line that formerly drove the LED.

**Comment by mrfoxie** [comment]
> This looks like a duplicate of https://forums.raspberrypi.com/viewtopic.php?t=369831 which has been answered, but anyway....
> 
> Pi Camera module v2 (https://www.raspberrypi.com/products/camera-module-v2/) has no LED. Only the v1 (discontinued since around 2015 due to ov5647 being declared EOL) has ever had an LED.
> 
> Pi02 was released in 2021, so 5-6 years after the v1 had been discontinued, and due to a shortage of GPIOs from the SoC it has no connection to the line that formerly drove the LED.

oops sorry its v1.3 my bad i think i need to get glasses🥸

**Comment by 6by9** [comment]
As has now been stated twice on the linked forum thread and once here, there is no connection to the camera LED on a Pi02, so there is no way to turn it on from the SoC.

The same is true on the Pi4 and Pi5.
The libcamera stack hasn't been written to drive it even where there is a defined GPIO for it.

**Comment by mrfoxie** [comment]
okay thank you
