### ISSUE TITLE
Can't boot randomly with 'SanDisk Ultra 16GB MicroSDHC card + SD adaptor'

### ISSUE THREAD

**Issue by gyeben** [raspberrypi/firmware#206]
Sometimes, the Pi cannot boot with the mentioned card. It gives lots of error messages like these:

mmcblk0: error -110 transferring data, sector 136999, nr 225, cmd response 0x900, card status 0xb00

end_request: I/O error, dev mmcblk0, sector 136999

mmcblk0: error -110 sending stop command, original cmd response 0x900, card status 0xe00

mmc0: resetting ongoing cmd 25DMA before 4096/4096 [1]/[1] complete

mmc0: Timeout waiting for hardware interrupt - cmd12.

So I have to re-image the card every other day. Is there something I can do to make the card work perfectly? More details: http://www.raspberrypi.org/phpBB3/viewtopic.php?f=63&t=53569&p=409669#p409669

**Comment by mirceade** [comment]
Hmm, just happened to me twice with an Adata SDHC class U1 microSD card. 
The workaround worked!
Why isn't this in the default configuration for the Raspbian?

**Comment by popcornmix** [comment]
Could you explain what workaround you applied?
Also report what "uname -a" reports.

**Comment by mirceade** [comment]
I've applied the second suggestion, ElanHasson's.
I had the exact same symptoms described by gyeben in the issue description.
Happened to me once before upgrading and the second time after the update, when the kernel version was the one below:
 
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux

**Comment by popcornmix** [comment]
sdhci-bcm2708 driver is not present in your kernel, so the "workaround" is purely placebo.

**Comment by mirceade** [comment]
Then that's one hell of a placebo! Let me describe my full experience:
After 3 restarts since first installing the OS, the boot crash occurred, and it refused to boot no matter  how many restarts I did afterwards.
So I reformatted the card and reinstalled raspbian.
After 3-4 restarts since that (rpi-update included after first boot) the issue resurfaced. I tried again re-booting 3 times but to no avail.
I've found this github issue and applied the fix with:
> dhci-bcm2708.missing_status=0 sdhci-bcm2708.sync_after_dma=0 sdhci-bcm2708.extramessages=1 sdhci-bcm2708.spurious_crc_acmd51=1
by editing the card on my laptop.
Immediately after that, raspberry booted just fine and it has done so for the last 7-8 restarts.

If the issue reappears I will retract my affirmation, but something must have been altered by the aforementioned placebo.

**Comment by nickaein** [comment]
Any updates on this issue?

**Comment by pelwell** [comment]
1) Use the latest Raspbian (Jessie) release. It includes improvements to the bcm2835-mmc driver.
2) If you still have SDCard problems, add this line to your config.txt (and reboot):
```
dtoverlay=sdhost
```
This Device Tree overlay selects a driver that uses the other SD/MMC interface in the BCM2835 chip, and reconfigures the pins so that it can access the SD card slot. If this works reliably you can try overclocking the SD interface:
```
dtoverlay=sdhost,overclock_50=62
```
or even
```
dtoverlay=sdhost,overclock_50=83
```
which will set the SD card clock to 62.5MHz and 83.3MHz, respectively. The clock speed is limited to integer divisions of the core clock (normally 250MHz), so 250/5=50, 250/4=62.5, 250/3=83.3. The driver will automatically select the nearest possible clock not exceeding (except for the fractional part) the value given (in MHz). If it detects some unreliability it will automatically increase the divisor to reduce the overclock, adding a warning to the kernel message log.

**Comment by nickaein** [comment]
Thanks @pelwell for the prompt and thorough response. Will give them try.
