### ISSUE TITLE
VideoCore: zero-copy support for image processing/rendering

### ISSUE THREAD

**Issue by julianscheel** [raspberrypi/firmware#218]
As a follow up to issue https://github.com/raspberrypi/firmware/issues/213 we need some way to support zero-copy usage of the different VideoCore modules like video_decoder, image_fx and video_renderer without being forced to use tunelled mode.

The background for this is the ability to gain best possible video performance with mediaplayers like VLC which have their own module concept, which is not well suited to integrate tunnells that span over multiple processing steps. Seeing that we have a working OMX implementation in VLC in which we can use video_decoder, image_fx and video_renderer in dedicated modules, it would be nice to have a way to do this with OMX. If this is not possible or alternatives (like MMAL) are preferred, we're open for this.

So to sum up the requirements:
1. Zero-copy of data buffers between components
2. Components can run independently, so that they can be adapted into existing multimedia framework architecture (VLC, gstreamer, etc.)
3. Performance should be sufficient to pass H264 Full HD video through a decoder, deinterlacer and render it to the screen - just like it can be achieved with omxil tunnels as of now.

Being able to map GPU buffers to ARM buffers is not a must-have from our point of view. Still for some things it would be a nice to have feature.

So what options do we have to achieve this goal? We are willing to support you with whatever we can and in the end provide an implementation of this within VLC, which will push RPi forward once more in the multimedia area.

**Comment by jvcleave** [comment]
@ghollingworth I am curious about this comment
"I think you can do this sufficiently well with MMAL, I'm not sure if OMX is ever going to have the capability. "

Doesn't MMAL just wrap OpenMax underneath the hood?
https://github.com/raspberrypi/userland/blob/master/interface/mmal/openmaxil/mmalomx_util_params_misc.c#L142

**Comment by luked99** [comment]
MMAL and OpenMAX/IL are two different ways of talking to the underlying "RIL" components that run on VideoCore, where RIL stands for "Reduced IL". Because MMAL is a proprietary API, it is much better suited for some tasks that OpenMAX/IL could ever be, and is also a lot simpler as it doesn't have to worry about all the horrible corner-cases in OpenMAX/IL.

**Comment by 6by9** [comment]
MMAL was designed as a more flexible replacement for IL. The IL core functionality probably hasn't been touched for 3-4 years, but had been maintained as a legacy tick box (some customers wanted to see IL compatibility on spec sheets). MMAL therefore has more tricks in the arsenal.

interface/mmal/openmaxil is not actually used for the mapping from a MMAL client to the RIL components. It was used the other way around under Android where codecs are exposed as IL components (ie IL client, mapped to MMAL, and further mapped on VC to RIL).

**Comment by jvcleave** [comment]
Thanks for the insights!

My main interest lies in trying to get pixel access from video/camera. I am able to do this with OpenMax's `OMX_UseEGLImage` and `egl_render` component but while updating my apps/looking for a faster alternative to `glReadPixels` I ran across these articles

https://vec.io/posts/faster-alternatives-to-glreadpixels-and-glteximage2d-in-opengl-es
https://software.intel.com/en-us/articles/using-opengl-es-to-accelerate-apps-with-legacy-2d-guis

When I first wrote these apps MMAL didn't have anything like the `egl_render` but I came across this
https://github.com/raspberrypi/userland/commit/d2c9f912da389c23ed27e81e940be3540f64fc59

Do you guys think there is any MMAL tech that would make it faster than OpenMax?

**Comment by julianscheel** [comment]
@jvcleave When you don't need YUV planes to be individual textures in your GL context you can do it like this as well https://github.com/raspberrypi/userland/commit/0d486513f56453f8203c270fcad0b04f8e4f1fee - I don't know  in how far they differ performance-wise though. Probably @6by9 can tell you.

**Comment by luked99** [comment]
That suggestion of using GL above looks like a good suggestion, although
it's probably doing an extra conversion on the GPU (YUV->ARGB-tiled->ARGB).

I wonder if it would be possible to create a pipeline of components
involving:

 - camera (video output, in YUVUV)
 - video_convert (read in YUVUV, output RGB)

And set the flag on the output of the video-converter to make it use
zero-copy buffers.

(I'm assuming the video_convert component will do what it says on the tin).

The main problem with this is that the zero-copy buffer support relies on a
driver called "vcsm" which does shared-memory allocation between VC and
ARM. That doesn't seem to be enabled at present, but perhaps we could ask
the foundation to take a look.

The GL route is probably easier if you want something right now.

**Comment by luked99** [comment]
If you don't use vcsm then there will be an extra copy via VCHIQ, which
will use the DMA engine. It's not ideal but it may not be that bad. It will
certainly be no worse than glReadPixels(), and possibly quite a lot better.

**Comment by popcornmix** [comment]
@luked99 vcsm is shipped as a kernel module and does work (e.g. with mmalplay).

**Comment by julianscheel** [comment]
Is vcsm required for zerocopy in general? Or only for zerocopy using video_convert to read back to arm memory?

**Comment by luked99** [comment]
vcsm is what MMAL will use if you set the zerocopy flag on the MMAL port.
It will use vcsm to allocate the buffers that get used, and you'll only get
a single set of shared buffers, rather than two sets of buffers (ARM,
VideoCore) with VCHIQ copying between them.

**Comment by julianscheel** [comment]
This is interesting, my kernel has CONFIG_BCM_VC_SM not set - and I always assumed that zerocopy works - at least I did not see any errors activating it and the performance is clearly better than without it. (pipeline is codec->image_fx->video_render, when zerocopy is enabled I just push these 64bit reference handles between the modules)

**Comment by popcornmix** [comment]
Any kernel from last few months should have VC_SM enabled:
pi@raspberrypi:~ $ zcat /proc/config.gz |grep VC_SM
CONFIG_BCM_VC_SM=y
Zero copy won't help when using opaque pointers - only when the ARM needs access to the output (e.g. decoded pixel) data.

**Comment by julianscheel** [comment]
@popcornmix I do have a custom kernel config, this is why it is not enabled. Anyway zerocopy vs opaque is of course the difference. I was too focussed on zerocopy to even think about that I'm using opaque mode :)

**Comment by 6by9** [comment]
Coming back to @jvcleave 's comment about wanting access to the pixel data. What do you want to do with it? If you're just after RGB data then the camera component can spit out RGB888 and RGBX32 directly. That doesn't really help too much if you're wanting to process it with GL, but you don't say that that is your goal. Removes the need for video_convert in @luked99 's pipeline. RaspistillYUV (in userland repo) has an example of requesting RGB888 (actually BGR888, but RGB888 is also supported along with BGR32 - the V4L2 driver allows you access to all of those)

Enabling zero copy on top of that will remove a memcpy in VCHI - VCSM only got enabled a few months ago as there was an issue where it didn't play well with the cutdown firmware (used for very low GPU memory allocation scenarios).

Going via GL will involve a conversion to RGB tile format (used by the 3D), and back again to raster order on readPixels. Fine if you want to process on the QPU, but otherwise not very efficient.

Opaque vs zero copy are two different things. Opaque buffers are only about 80 bytes, so taking a copy of them isn't a big deal. 
Saving the copy when dealing with genuine pixel buffers is a useful saving that can be done with zero copy. I haven't used it on Pi, but it was used heavily elsewhere (it's on my todo list to convert the userland apps to use it, and for V4L2 if I can).

**Comment by jvcleave** [comment]
@6by9 the main use for pixel access would be for OpenCv type operations. Although OpenCv will still hit the CPU I am thinking with the RPI2 (and possible OpenCv NEON support) it could be much more usable.

the `egl_render` is pretty good for up to 720p and allows shaders to be applied. When I ran across the Zero Copy options I was hoping that it may speed things up for 1080p.

**Comment by 6by9** [comment]
OpenCV works quite nicely via V4L2 (you need to force bcm2835-v4l2 to use video mode though), or others have been doing it via picamera and Python with fairly reasonable results - have a look on the forums.. 
If you want shaders then you have the right approach, but I don't believe there is an easy zero copy option via GL/readPixels.
NB egl_render defaults to dropping frames if the frames come in too fast, so you may not achieve the frame rate you think you do. OpenCV via V4L2 ended up stalling very badly with 100% CPU usage if the sensor was producing images faster than it could consume them.

**Comment by jvcleave** [comment]
V4L2 is using MMAL correct?

**Comment by 6by9** [comment]
Yes, V4L2 is using MMAL underneath but has to recreate userland libraries due to licencing-type issues. 
MMAL, IL, and V4L2 all use the same core code on VideoCore.
V4L2 doesn't currently use zero copy as it needs to hook into videobuf2 and the ways that can map memory. I believe it can be done, but need some time to look into it (map a vcsm allocation as dmabuf and expose that).

**Comment by luked99** [comment]
If you just want fast access to the pixel data in RGB format then I think 6by9's suggestion above of using the camera, but setting the output format to RGB, should be the easiest way right now.

As noted above, it will do fewer conversions on VideoCore (YUV->RGB, vs YUV->RGB-Tiled->RGB) and will give you better concurrency (there are more buffers around so more things can be happening at once, plus GL really doesn't work well if you have to query the server).

If you can enable zero-copy on the buffers that will eliminate VCHIQ's DMA of the pixel data.

You could probably experiment with the really rather wonderful Python Camera module, if you're not using it already.

https://pypi.python.org/pypi/picamera/

One thing I noticed recently is that, at least when converting textures, conversions to/from ARGB32 go quite noticeably faster than conversions to/from RGB24, so that might also help a bit. (Maybe that's obvious though, I don't know).

**Comment by julianscheel** [comment]
Would a mmal pipeline with ports configured as zerocopy using vmcs be any slower compared to an opaque mmal pipeline?

**Comment by luked99** [comment]
It should be pretty much the same.

**Comment by 6by9** [comment]
Actually I'll disagree with luked99 there. There will be a potentially significant difference.

Opaque buffers can be in an optimised image format to minimise the conversions required. Zero copy buffers have to be in the defined format, so that may well require a format conversion into the buffer at the source component, and then a conversion back out of the buffer into the format required by the hardware in the sink component. This is certainly the case with camera to video encode.

Opaque buffers also allow components to share an underlying buffer. So in the case of video decode, to video scheduler, to video render, when using opaque buffers a reference to the underlying image that video decode produced will be forwarded on to render. 
With zero copy buffers, decode will have to format convert into the buffer, scheduler hold that converted image, and then memcpy (possibly format convert) it into the buffer allocated for forwarding on to render.

Just to add further confusion, you can zero copy opaque buffers - remember zero copy just controls where and how the buffer is allocated. Opaque is an encoding of what goes in that buffer. Zero copy will make little difference on opaque buffers anyway - for buffers that will fit within the control message, VCHI will put the buffer payload in there. At something like 64 bytes for an opaque buffer, this is what happens generally.

**Comment by luked99** [comment]
For what's being done here (getting RGB pixels out of the camera) I don't
think there will be any difference. The whole point is to do that
conversion on VideoCore.

**Comment by julianscheel** [comment]
@luked99 Actually the use-cases in this topic got a bit mixed up. My use-case which was originally discussed in the topic is video decoding -> image_fx (deinterlace) -> display. The rgb camera grab use case came in when @jvcleave hijacked the topic :)

So following what @6by9 describes it should have a siginifcant impact on my use case and hence it's not really worth implementing it in VLC as an alternative to the opaque chain. The main reason why I thought about is that is might ease the buffer handling in VLC a bit.

**Comment by luked99** [comment]
Ahh, ok, that makes sense. For your use case, as 6by9 said, opaque is 
the way to go.

Can you expand on "ease the buffer handling VLC" ?

Thanks!
Luke

**Comment by julianscheel** [comment]
@luked99 
VLC has a concept of picture pools owned by the video output plugin. So the video output plugin is the one who normally allocates pictures and other plugins (decoders, filters) acquire pictures from that pool. Now with mmal opaque mode the owner of the pictures is actually the codec or image_fx module, which forces us into some kind of a hack. We create a picture pool of vlc-pictures which are later on dynamically attached to mmal_buffer_headers from the codec. While this works well in principle, it becomes a bit problematic when it comes to the lifecycle of individual modules - ie in VLC a picture is expected to be valid as long as the vout is alive, which is not true when using mmal opaque buffers. So far I tried to cope with that by synchronising the filter and render methods, so that I am sure no buffers would be in transit when the codec is shut down, but this causes deadlocks. My newest approach is using mmal_component_acquire to ensure the picture creating component is kept alive until all buffers are released, but this does not avoid the actual deadlocks.

This is related to https://github.com/raspberrypi/firmware/issues/377 where I run into deadlocks in mmal/gpu code on certain coditions like applying a video format change (stream changes aspect ratio) almost simultaneously with destroying a component, etc.
I tried several things to avoid getting into these cases but so far I was only able to spot more and more slightly different freezes - I guess all have the same root-cause. I fear I won't get any further there without being able to see what's going on in the GPU when the stall occurs...

In case you have some ideas about this I'd be glad if you joined https://github.com/raspberrypi/firmware/issues/377 and take a look at the testcase I provided here: https://github.com/raspberrypi/firmware/issues/377#issuecomment-78267842
