### ISSUE TITLE
video_decode internal buffering/queuing

### ISSUE THREAD

**Issue by MuhammadD** [raspberrypi/firmware#232]
Hi,

I've got a simple H.264 decoder pipeline set up (video_decode->resize) and I'm able to decode an incoming H.264 stream.

The stream is special in that it only consists of I and P frames and I know exactly how many encoded bytes there are per frame, so I'm able to pass a full frame per OMX buffer (or buffers) to the decoder, and specify OMX_BUFFERFLAG_ENDDOFFRAME. I've also ensured, as per documentation, that OMX_DataUnitCodedPicture is set. Also, "max_frame_dec_buffering" is set to "1" to minimize any extra latency.

What I'm finding is that the decoder is lagging by about 2 frames. Is there any way to avoid this? I am aware the documentation states that it may do some level of internal buffering, but this really doesn't help here. In comparison, my FFmpeg decoder is able to generate immediate output.

Is there anyway to eliminate this buffering, or flushing the decoder after each input frame is given to it? If not, would it be possible to add?

Thanks in advance!

**Comment by KostjaStein** [comment]
@popcornmix 

> For special-case use, if you know that the streams are always non-reordered, you can override what the stream says about max_dec_frame_buffering and reordering limits with VIDEO_DECODER_CONFIGURE_COMPONENT. This is helpful since lots of streams don't bother to include VUI, at which point you don't have enough information to constrain things appropriately.

Could you please give me some guidance regarding the "VIDEO_DECODER_CONFIGURE_COMPONENT". I searched the net for it but was unable to find anything appropriate.

My background:
I've got a stream from an ip-camera (3fps, 352x240 pix) which I would like to decode. This stream has no VUI so I'm trying to set max_dec_frame_buffering and reordering limits to the "video_decode" component. At the moment I get a decoding latency of 8-9 frames and would like to bring it down to 1-2 frames.

**Comment by deborah-c** [comment]
Dom is, I think, correct that the far easier solution, if you know for certain the characteristics of an incoming stream, is to inject appropriate data into the stream -- is the camera generating an SPS with a ridiculously high level for the resolution? Or is that coming from elsewhere? If so, simply changing the level is the easy fix. However, if that's not possible, than the CONFIGURE API is the right way to go.

To add a few notes:

MMAL/RIL transfers configuration data only at one point, quite early in the codec lifecycle. I don't have source access right now (but hope to fix that this week!), but Dom should be able to tell you which state change is involved.

The interface to MMAL allows multiple configuration blocks to be concatenated. I *think* the size of the data written to it is used as a limit, rather than a terminating structure. Again, Dom can confirm.

The API files were intended to be part of the declared Codec interface; they do require care, since you can break the codec with them, which is why they're not part of the main interface, but we should really publish them as part of the userland. There are similar configuration structures for other elements of the decoder's internal structure, which might conceivably be useful to some people.

(The API is rather baroque because it's intended to continue working without change to the client, if the codec provides new parameters (as has happened a handful of times, and because it's a control structure for a designed-but-unimplemented layering system for post-processing that was mooted. Sorry!)

**Comment by longo92-vrmedia** [comment]
> As I said before this is beyond my knowledge so my help is limited. This is very much meddling with test options rather than a supported API. I think this is unlikely to work. I think you may be better off injecting a VUI into video bitstream. But..
> 
> `OMX_IndexParamBrcmVideoDecodeConfigVD3` is the OMX parameter to set `VIDEO_DECODER_CONFIGURE_COMPONENT`. See [here](http://mirrors.neusoft.edu.cn/rpi-firmware/documentation/ilcomponents/prop.html).
> 
> ```
> /*
>  * All configuration request structures begin with this common part.
>  *
>  * component contains a module identifier (codec_module_t), which
>  * indicates to which component the configuration request is directed.
>  *
>  * config_requests contains a bitmask which indicates which configuration
>  * elements are active in this request, i.e. elements for which the
>  * configuration should be updated.
>  *
>  * config_override contains a bitmask which indicates which configuration
>  * elements should have overriding values set by this request. If a bit
>  * is set in config_requests, and the corresponding bit is clear in
>  * config_override, then the request is to restore default operation for
>  * that configuration element. It is an error to set a config_override
>  * bit without setting the corresponding config_active bit.
>  *
>  * Bitmask values are defined by each individual configuration structure.
>  */
> 
> typedef struct vd3_configure_t {
>    uint32_t   component;         // codec_module_t
>    uint32_t   config_size;       // size of this structure
>    uint32_t   config_requests;   // bitmask of requests in this block
>    uint32_t   config_override;   // bitmask of override requests
> }  VD3_CONFIGURE_T;
> 
> typedef struct vd3_configure_dpb_t {
>    VD3_CONFIGURE_T  common;
>    uint32_t         multiview_enable;    // boolean
>    uint32_t         num_reorder_frames;  // unsigned integer
>    uint32_t         max_dpb_frames;      // positive integer
> }  VD3_CONFIGURE_DPB_T;
> 
> /* Bitmasks for config_request and config_override */
> enum {
>    VD3_CONFIGURE_DPB_MULTIVIEW_ENABLE   = 0x00000001, // internal use only
>    VD3_CONFIGURE_DPB_NUM_REORDER_FRAMES = 0x00000002,
>    VD3_CONFIGURE_DPB_MAX_DPB_FRAMES     = 0x00000004,
> 
>    VD3_CONFIGURE_DPB_ALL                = 0x00000007
> };
> ```
> 
> the component should be:
> 
> ```
> CODEC_MODULE_H264DPB     = 5
> ```
> 
> I think config_requests and config_override should be set to `VD3_CONFIGURE_DPB_NUM_REORDER_FRAMES` and/or `VD3_CONFIGURE_DPB_MAX_DPB_FRAMES`
> 
> and you send the structure `VD3_CONFIGURE_DPB_T`.

In which source file is located the following define?
CODEC_MODULE_H264DPB     = 5
