### ISSUE TITLE
Raspberry Pi freezes roughly after 1 day and 15 hours (on average) when playing audio files (*.wav)

### ISSUE THREAD

**Issue by hid3nax** [raspberrypi/firmware#247]
Raspberry Pi (running latest Raspbian with all updates) freezes roughly after 1 day and 15 hours (on average) when playing audio files (*.wav).

The system is running headless.
The system is running off a 3.5" HDD (powered separately).
The system does not have any devices connected except USB HDD and ethernet cable.
TP1 and TP2 Voltage is around 4.89 V.
Analogue output is being used, routed to an amplifier.
'ifplugd' package was removed/purged to save some interrupts.
The system is most up to date (apt-get update, upgrade). The kernel is latest version for now:
Linux safira 3.10.25+ #622 PREEMPT Fri Jan 3 18:41:00 GMT 2014 armv6l GNU/Linux

The mpd player is used to play *.wav files.
The music is being played only on time between 9AM till 8 PM. The Pi hangs only when playing music, on the 2nd day of uptime.

What has been done to eliminate the issue (didn't help anything of the listed):
The mpd is being stopped and started nightly by a cron script.
The music files are being played from USB HDD. I've moved it to SD card but that didn't help.
Swap space has been increased to 200 MB.
minfreekbytes in sysctl was increased to 16 MB.
The following sysctl values were set:
kernel.panic = 4
kernel.panic_on_oops = 3
Unfortunately, the Pi does not reboot after the hang up.

The only way to recover the Raspberry Pi again is to unplug and then plug the power.

After the reboot, neither syslog (syslog/messages/kern.log/auth.log or mpd.log) do not report anything.

The system is being graphed in Cacti at 5 minute intervals. The last values before the system hangs do not report anything unusual (memory/cpu/interrupts are in normal range).

If any further information or output is needed, please reply.

**Comment by kprkpr** [comment]
For know to all lastest commit of 3.6.11+ Rpi Hexxeh , they took me a lot of time for find out..
https://github.com/Hexxeh/rpi-firmware/tree/8234d5148aded657760e9ecd622f324d140ae891

sudo rpi-update 8234d5148aded657760e9ecd622f324d140ae891

uname -a
Linux raspberrypi 3.6.11+ #557 PREEMPT Wed Oct 2 18:49:09 BST 2013 armv6l GNU/Linux

**Comment by pelwell** [comment]
What are you saying about that commit? Is it good or bad?

**Comment by kprkpr** [comment]
Well..Im sharing this because up it talks about 3.6.11+ doesnt have this bugs, and I thought is easier to install having the commit and command 

Before I tried with pastebin attached up, but they didnt worked for me

Im trying it right now, im not sure about it works, but if it's a bug of 3.10.y kernels, this may work (Trying with mpd,streaming, but I have same bug as that)

**Comment by ajohn370** [comment]
Having a similar issue with an rpi 3 b. System runs smoothly but it freezes hangs and I loose ssh and VNC access. Pi is simply displaying a flash webpage that displays the status of one of our systems. It is not monitoring the system Just a webpage that displays the systems status. It should not be pulling a lot of cpu power.

I thought the freezing was due to over heating because  I would See temperature icon. The PI is in a temperature controlled room and I placed heat sinks on the chips. However the Pi kept freezing and Webpage would be up but it would not actively update the stats. I still would loose access to PI.

I under clocked the Pi down to 600 mhz now pi continuously updates the webpage but I still loose access to the Pi through SSH and VNC.

**Comment by mirabilos** [comment]
Same here, but without USB.

RPi 1B, only power and ethernet connected, running stock Debian/armel, but with upgraded `raspi-firmware` (`1.20240424+ds-2`).

On bullseye, it ran stable. After an upgrade to bookworm (because armel isn’t in LTS) I get occasional crashes… one when not actively doing anything (so perhaps a cronjob?), and now that I put AdGuard Home on it so the system is actually under load, about once every 1–2 days.
