### ISSUE TITLE
mmcblk0 error -110 errors

### ISSUE THREAD

**Issue by whit33r** [raspberrypi/firmware#302]
"mmc0: Timeout waiting for hardware interrupt"

3.12.24+ kernel (and previous versions), continuously gives me mmcblk errors.
Then i noticed when the webserver return "404".
Sometimes it work for 1 month, but usually only works for few days.

Kingston SDC10/8GB : Pi B model 512mb RAM //non-oc

**Comment by Ruffio** [comment]
@elpetak is this still an issue?

**Comment by elpetak** [comment]
Well, funny that you ask.
I haven't had any SD issues for a very long long time but then I had my PI offline for a few weeks and yesterday I found out the new firmware had kernel 4.x so I updated to it.
I can't say I have these same issues, but I did have some corruption last night while simultaneously doing some "apt-get install" and "rm -rf" which is why I was reviewing these reports and found your question (I must have missed the github notification email).
I might try the new sdhost overlay and see how it goes.
For the time being I've also slightly reduced my overclock settings just in case.

**Comment by popcornmix** [comment]
@elpetak if you can find a repeatable way of provoking corruption that would be useful.
Ideally from a clean raspbian install (it's always possible the corruption occurred long ago and you just happened to discover it with the commands you were running).

Remove overclock when testing, and testing the sdhost driver would be useful.

**Comment by elpetak** [comment]
Since the episode 2 days ago it's been rock solid.
I blame this last event to a combination of barely-good-enough power source and that I was testing a different Wifi driver while I was also causing a high I/O load on the SD card.
I'm not really having any issues now.

**Comment by Ruffio** [comment]
@whit33r can this issue be closed or are you still experiencing it?

**Comment by whit33r** [comment]
Everything's okay.
