### ISSUE TITLE
Module w1_therm no longer exist

### ISSUE THREAD

**Issue by mati75** [raspberrypi/firmware#338]
Hello, 

After update to branch next with kernel:

Linux malina 3.18.1+ #731 PREEMPT Fri Dec 19 19:16:36 GMT 2014 armv6l GNU/Linux

In load module w1-term modprobe return:

modprobe: FATAL: Module w1-term not found.

On 3.18.0+ problem doesn't exist.

**Comment by mati75** [comment]
Yes, I make a typo:

```
mati75@malina ~ % lsmod | grep w1
w1_therm                3325  0 
w1_gpio                 4068  0 
wire                   31280  2 w1_gpio,w1_therm
mati75@malina ~ % uname -a
Linux malina 3.18.0+ #726 PREEMPT Mon Dec 8 16:01:09 GMT 2014 armv6l GNU/Linux
```
and after update this like this:
```
w1_therm                3325  0 
w1_gpio                 4068  0 
wire                   31280  2 w1_gpio,w1_therm
mati75@malina ~ % uname -a
Linux malina 3.18.1+ #731 PREEMPT Fri Dec 19 19:16:36 GMT 2014 armv6l GNU/Linux
```
but the w1 devices is no longer exists. After the downgrade to stable branch is correct.

**Comment by pelwell** [comment]
Can you please give proper before and after examples showing how it used to be and how it is now? I can't understand what has changed.

**Comment by mati75** [comment]
For example on 3.12.35+ I see:
```
mati75@malina /sys/bus/w1/devices % ls -la
total 0
drwxr-xr-x 2 root root 0 Jan  5 22:59 ./
drwxr-xr-x 4 root root 0 Jan  5 22:41 ../
lrwxrwxrwx 1 root root 0 Jan  5 22:59 28-00000463d0ed -> ../../../devices/w1_bus_master1/28-00000463d0ed/
lrwxrwxrwx 1 root root 0 Jan  7 18:30 w1_bus_master1 -> ../../../devices/w1_bus_master1/
```
On 3.18.1+ is nothing here, nothing hardware was changes. On 3.18.0+ is the same like 3.12.35+. I think is problem with upstream kernel, on the version compiled by myself is exactly the same problem.

**Comment by mati75** [comment]
On 3.18.2+ is the same problem.

**Comment by pelwell** [comment]
This is probably because the newer kernels are using device tree by default. In this mode, the board support code doesn't create the platform devices for the optional interfaces to avoid fighting over GPIO pins. You can revert to the old non-DT behaviour by adding "device_tree=" to your config.txt file, but you should really switch over to using device tree (if you haven't already) as future modules and devices may rely on it.

The correct solution is to add an overlay that enables w1-gpio support. I think I have this working, but:
1) the general solution requires updated firmware that, although imminent, isn't released yet, and
2) I haven't tested it with real onewire devices (although it ought to be OK because I haven't changed the driver at all).

If you tell me which pins you are using (the "gpiopin" and "pullup" module parameters) then I can give you a custom overlay .dtb file to test.

There is a Pi Forum thread discussing the device tree support [here](http://www.raspberrypi.org/forums/viewtopic.php?f=29&t=93015&sid=bead906b64f49e963161b17c5720f995), and a documentation [here](https://github.com/raspberrypi/documentation/blob/master/configuration/device-tree.md).

**Comment by pelwell** [comment]
The latest firmware release on the "next" branch includes the w1-gpio overlays and the loader that supports them.

To use the overlay, add:
```
dtoverlay=w1-gpio,gpiopin=4
```
to config.txt (where 4 should be replaced with your chosen pin). If you are using the external pull-up feature you will need to use the other overlay:
```
dtoverlay=w1-gpio-pullup,gpiopin=4,pullup=5
```
again using numbers appropriate for your setup.

If you experience problems with device tree and overlays, add:
```
dtdebug=1
```
to your config.txt, then use `sudo vcdbg log msg` to read the debug messages.

**Comment by mati75** [comment]
Add to /boot/config.txt line:
```
device_tree_overlay=overlays/w1-gpio-pullup-overlay.dtb
```
solved this issue.

**Comment by pelwell** [comment]
```
dtoverlay=w1-gpio-pullup
```
is the concise version of that.
