### ISSUE TITLE
No control over DVI mode on HDMI output

### ISSUE THREAD

**Issue by matiaspl** [raspberrypi/firmware#61]
There seems to be a problem with "DVI mode". I've tried two different monitors and a couple of firmwares. If I use a HDMI-DVI cable, I cannot change the resolution. It's fixed to 720p@60Hz. I can power off the HDMI output, but afterwards it's not possible to power it back on. It comes back only after a reboot. 

In DVI mode tvservice -m CEA and tvservice -m DMT show empty lists, -d gives zero length output file. If I use a HDMI-HDMI cable, everything works as expected.

**Comment by scirelli** [comment]
I'm having this issue too. I have an HDMI to DVI cable. 

Here's what I've tried to do to reproduce the problem. So I have a fresh image of Raspbian. Go through normal initial boot everything is fine. Resolution is fine. I startx, resolution is fine. I shut down the pi through the ui. Turn it back on, and the resolution is messed up. It's low resolution and I can't change it. 

This happened on my old Raspberry B+ and my A+. Same OS. 

I narrowed it down to shutting down, by starting over with a fresh image and just cutting the power to the Pi. I started it up again and the resolution was fine. Although some xml files were messed up because of the bad shutdown.

What is being written/configs being changed on shutdown that is causing this resolution problem??

**Comment by popcornmix** [comment]
The only file that affects HDMI/DVI mode is config.txt and that never gets written automatically.
What does
```
tvservice -s
tvservice -m CEA
tvservice -m DMT
```
report in the good and bad cases?

Can you try this procedure for saving the edid to a file:
http://kodi.wiki/view/Raspberry_Pi_FAQ#TV_is_not_detected_unless_powered_on_first
