### ISSUE TITLE
vcgencmd get_throttled on RPi3 returns unexpected value

### ISSUE THREAD

**Issue by Terminus-IMRC** [raspberrypi/firmware#615]
When I do ```vcgencmd measure_temp; vcgencmd get_throttled; vcgencmd measure_temp``` on RPi3, it sometimes output

```
temp=39.2'C
throttled=0x50000
temp=38.6'C
```

and sometimes
```
temp=38.6'C
throttled=0x50005
temp=38.6'C
```
(The over-temperature bit is on though the actual temperature is much lower than 85'C).

I'm using the latest firmware.

Is this reproducible on other RPi3? (Sorry but I have only one RPi3 now.)
I confirmed that this is NOT reproducible on RPi2B.

**Comment by popcornmix** [comment]
Actually bit 2 means you are currently throttled (turbo disabled). The forum post was incorrect there.
That may be either due to low voltage or over temperature.
If the low voltage bit is set and you are throttled then that implies over voltage.

So, for your results you are currently throttled due to low voltage. I suspect you also have a red/orange warning square on screen. You need a better power supply (temperature is not a problem).

**Comment by popcornmix** [comment]
I've edited the forum post to match the behaviour more accurately.

**Comment by Terminus-IMRC** [comment]
Thank you!

**Comment by Terminus-IMRC** [comment]
Note: The forum post is this: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=147781&start=50#p972790
