### ISSUE TITLE
USB 3.0 hub fails to pass through USB 2.0 devices (ID 2109:3431)

### ISSUE THREAD

**Issue by juliangilbey** [raspberrypi/firmware#64]
I have attached a powered USB Hub to my Raspberry Pi.  It shows up with lsusb:
Bus 001 Device 005: ID 2109:3431

When I attach this device to my Linux amd64 machine, running Linux 3.2.20, it is able to also show connected (USB 2.0?) devices to the machine, for example:
Bus 002 Device 004: ID 0458:002e KYE Systems Corp. (Mouse Systems) 

However, when I connect it to the Pi, it does not show the attached devices, which is rather unfortunate.

I imagine that this might be the same bug as in  https://bugs.launchpad.net/ubuntu/+source/linux/+bug/783097 but then again, maybe not.

On connecting the USB device to the hub, the following messages appear in dmesg (and also in /var/log/kern.log):

[ 1113.345672] usb 1-1.2.1: new low speed USB device number 10 using dwc_otg
[ 1113.425796] usb 1-1.2.1: device descriptor read/64, error -71
[ 1113.615712] usb 1-1.2.1: device descriptor read/64, error -71
[ 1113.805702] usb 1-1.2.1: new low speed USB device number 11 using dwc_otg
[ 1113.885695] usb 1-1.2.1: device descriptor read/64, error -71
[ 1114.075687] usb 1-1.2.1: device descriptor read/64, error -71
[ 1114.265688] usb 1-1.2.1: new low speed USB device number 12 using dwc_otg
[ 1114.685460] usb 1-1.2.1: device not accepting address 12, error -71
[ 1114.765669] usb 1-1.2.1: new low speed USB device number 13 using dwc_otg
[ 1115.185455] usb 1-1.2.1: device not accepting address 13, error -71
[ 1115.185811] hub 1-1.2:1.0: unable to enumerate USB device on port 1

Any clues?

Thanks!

Julian

**Comment by fdominguezr** [comment]
Hi!

I'm having the same issues with a Raspberry Pi B+ running OpenELEC 5.0.0 (kernel Linux 3.17.7) with Kodi 14.0 and the [CoolBox 7 ports Hub USB](http://www.coolbox.es/en/products/hub-7-ports-usb-3-0/), it has 4 ports 3.0 and 3 ports  2.0, but it fail to deliver consistent compatibility even with 2.0 devices... 

![hub-usb-7-puertos](https://cloud.githubusercontent.com/assets/3350033/5998388/fdb6a4b8-aac6-11e4-8bec-149f8084ef73.jpg)

It can uses a WiFi dongle via a USB 2.0 hub port (but does not work in any 3.0 ports), but this hub does not work with an external HDD, nor with a wireless keyboard by USB. This USB hub also connects fine a usb memory stick at USB 2.0 and 3.0 ports.

I suspect it is because it uses chipset with famous  ID 2109:2812...

USB devices conected right now are:

OpenELEC:/ # lsusb
Bus 001 Device 008: ID 059b:047a Iomega Corp. Select Portable Hard Drive
Bus 001 Device 007: ID 0bda:8176 Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter
Bus 001 Device 006: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 004: ID 2109:2812
Bus 001 Device 005: ID 062a:4101 Creative Labs
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Branches for USB devices are:

OpenELEC:/ # lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/5p, 480M
        |__ Port 1: Dev 3, If 0, Class=Vendor Specific Class, Driver=smsc95xx, 4   80M
        |__ Port 2: Dev 5, If 0, Class=Human Interface Device, Driver=usbhid, 12   M
        |__ Port 2: Dev 5, If 1, Class=Human Interface Device, Driver=usbhid, 12   M
        |__ Port 3: Dev 4, If 0, Class=Hub, Driver=hub/4p, 480M
            |__ Port 1: Dev 6, If 0, Class=Hub, Driver=hub/4p, 480M
                |__ Port 4: Dev 7, If 0, Class=Vendor Specific Class, Driver=rtl   8192cu, 480M
        |__ Port 5: Dev 8, If 0, Class=Mass Storage, Driver=usb-storage, 480M


And lsusb -v gives for this device this information just in case it helps:

Bus 001 Device 010: ID 2109:2812
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.10
  bDeviceClass            9 Hub
  bDeviceSubClass         0
  bDeviceProtocol         1 Single TT
  bMaxPacketSize0        64
  idVendor           0x2109
  idProduct          0x2812
  bcdDevice           90.80
  iManufacturer           1 VIA Labs, Inc.
  iProduct                2 USB2.0 Hub
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           25
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12
Hub Descriptor:
  bLength               9
  bDescriptorType      41
  nNbrPorts             4
  wHubCharacteristic 0x00e0
    Ganged power switching
    Ganged overcurrent protection
    TT think time 32 FS bits
    Port indicators
  bPwrOn2PwrGood       50 * 2 milli seconds
  bHubContrCurrent    100 milli Ampere
  DeviceRemovable    0x00
  PortPwrCtrlMask    0xff
 Hub Port Status:
   Port 1: 0000.0503 highspeed power enable connect
   Port 2: 0000.0100 power
   Port 3: 0000.0100 power
   Port 4: 0000.0100 power
Binary Object Store Descriptor:
  bLength                 5
  bDescriptorType        15
  wTotalLength           42
  bNumDeviceCaps          3
  USB 2.0 Extension Device Capability:
    bLength                 7
    bDescriptorType        16
    bDevCapabilityType      2
    bmAttributes   0x00000002
      HIRD Link Power Management (LPM) Supported
  SuperSpeed USB Device Capability:
    bLength                10
    bDescriptorType        16
    bDevCapabilityType      3
    bmAttributes         0x00
    wSpeedsSupported   0x000e
      Device can operate at Full Speed (12Mbps)
      Device can operate at High Speed (480Mbps)
      Device can operate at SuperSpeed (5Gbps)
    bFunctionalitySupport   1
      Lowest fully-functional device speed is Full Speed (12Mbps)
    bU1DevExitLat           4 micro seconds
    bU2DevExitLat         231 micro seconds
  Container ID Device Capability:
    bLength                20
    bDescriptorType        16
    bDevCapabilityType      4
    bReserved               0
    ContainerID             {2d207069-441e-de4c-8f73-78ec5964eca7}
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0001
  Self Powered

Recap: I just wrote to CoolBox support giving all this information, let's see what they can do... If you have any idea please don't hesitate to tell me. Thanks! ;-)

Kind regards,
Francisco

**Comment by SpiRaiL** [comment]
Does anyone know if the new Pi 2 will still have this issue?

**Comment by P33M** [comment]
The USB phy is identical between BCM2835 and BCM2836.

**Comment by Thireus** [comment]
@SpiRaiL, yes same issue with the Pi 2. :(

**Comment by Thireus** [comment]
I've just tried to put a USB 2.0 hub in-between the USB 3.0 hub and the Raspberry Pi. Result is exactly the same as if there were no USB 2.0 hub.

Still stuck with these "device descriptor read/64, error -71" error if dwc_otg.speed=1 is not set. But I really want to use my USB 3.0 hub at high speed...

**Comment by Thireus** [comment]
Desperate bump...

**Comment by P33M** [comment]
There is no fix possible that will allow the use of full- and low-speed devices behind USB3.0 hubs with the ViA chipset without a firmware upgrade from the silicon vendor, as explained multiple times previously.
